/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author DWI WAHYU
 */
public class vShop extends javax.swing.JFrame {

    /**
     * Creates new form vHalamanDokter
     */
    public vShop() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void klikkembali(ActionListener action) {
        kembali.addActionListener(action);
    }
    public JButton getBtnUpgrade1 (){
    return btn_upgrade1 ;
}
    public JButton getBtnUpgrade2 (){
    return btn_upgrade2 ;
}   
    public JButton getBtnUpgrade3 (){
    return btn_upgrade3 ;
}
    public JLabel Item1 () {
        return lbl_item1 ;
    }
    public JLabel Item2 () {
        return lbl_item2;
    }
    public JLabel Item3 () {
        return lbl_item3 ;
    }
    public JLabel NamaItem1() {
        return lbl_nama1 ;
    }
    public JLabel NamaItem2() {
        return lbl_nama2 ;
    }
    public JLabel NamaItem3() {
        return lbl_nama3 ;
    }
    public JLabel HargaItem1 (){
        return lbl_harga1;
    }
    public JLabel HargaItem2 (){
        return lbl_harga2;
    }
    public JLabel HargaItem3 (){
        return lbl_harga3;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kembali = new javax.swing.JButton();
        btn_upgrade1 = new javax.swing.JButton();
        btn_upgrade3 = new javax.swing.JButton();
        btn_upgrade2 = new javax.swing.JButton();
        lbl_item1 = new javax.swing.JLabel();
        lbl_item2 = new javax.swing.JLabel();
        lbl_item3 = new javax.swing.JLabel();
        lbl_nama1 = new javax.swing.JLabel();
        lbl_nama2 = new javax.swing.JLabel();
        lbl_nama3 = new javax.swing.JLabel();
        lbl_harga1 = new javax.swing.JLabel();
        lbl_harga2 = new javax.swing.JLabel();
        lbl_harga3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SP_Back_Button.png"))); // NOI18N
        kembali.setBorder(null);
        kembali.setContentAreaFilled(false);
        kembali.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SP_Back_Button_MouseOver.png"))); // NOI18N
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 249, -1, 100));

        btn_upgrade1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SP_Upgrade_Button.png"))); // NOI18N
        btn_upgrade1.setBorder(null);
        btn_upgrade1.setBorderPainted(false);
        btn_upgrade1.setContentAreaFilled(false);
        btn_upgrade1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SP_Upgrade_Button_MouseOver.png"))); // NOI18N
        getContentPane().add(btn_upgrade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        btn_upgrade3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SP_Upgrade_Button.png"))); // NOI18N
        btn_upgrade3.setBorder(null);
        btn_upgrade3.setBorderPainted(false);
        btn_upgrade3.setContentAreaFilled(false);
        btn_upgrade3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SP_Upgrade_Button_MouseOver.png"))); // NOI18N
        getContentPane().add(btn_upgrade3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, -1, -1));

        btn_upgrade2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SP_Upgrade_Button.png"))); // NOI18N
        btn_upgrade2.setBorder(null);
        btn_upgrade2.setBorderPainted(false);
        btn_upgrade2.setContentAreaFilled(false);
        btn_upgrade2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SP_Upgrade_Button_MouseOver.png"))); // NOI18N
        getContentPane().add(btn_upgrade2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        lbl_item1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Kursi1.png"))); // NOI18N
        getContentPane().add(lbl_item1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        lbl_item2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Wifi1.png"))); // NOI18N
        getContentPane().add(lbl_item2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        lbl_item3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_item3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AC1.png"))); // NOI18N
        getContentPane().add(lbl_item3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 200, -1));

        lbl_nama1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbl_nama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 140, 30));

        lbl_nama2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbl_nama2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 140, 30));

        lbl_nama3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbl_nama3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 60, 20));
        getContentPane().add(lbl_harga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 90, 20));
        getContentPane().add(lbl_harga2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 90, 30));
        getContentPane().add(lbl_harga3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SP_background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vShop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_upgrade1;
    private javax.swing.JButton btn_upgrade2;
    private javax.swing.JButton btn_upgrade3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton kembali;
    private javax.swing.JLabel lbl_harga1;
    private javax.swing.JLabel lbl_harga2;
    private javax.swing.JLabel lbl_harga3;
    private javax.swing.JLabel lbl_item1;
    private javax.swing.JLabel lbl_item2;
    private javax.swing.JLabel lbl_item3;
    private javax.swing.JLabel lbl_nama1;
    private javax.swing.JLabel lbl_nama2;
    private javax.swing.JLabel lbl_nama3;
    // End of variables declaration//GEN-END:variables
}
